//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APISession2Auth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class historicos
    {
        public int cod_jog { get; set; }
        public System.DateTime dat_ini { get; set; }
        public int cod_time { get; set; }
        public Nullable<System.DateTime> dat_fim { get; set; }
    
        public virtual jogadores jogadores { get; set; }
        public virtual times times { get; set; }
    }
}
