//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APISession2Auth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jogadores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public jogadores()
        {
            this.historicos = new HashSet<historicos>();
        }
    
        public int cod_jog { get; set; }
        public System.DateTime dat_nasc { get; set; }
        public decimal salario { get; set; }
        public int cod_pos { get; set; }
        public string nom_jog { get; set; }
        public Nullable<int> cod_time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historicos> historicos { get; set; }
        public virtual posicoes posicoes { get; set; }
        public virtual times times { get; set; }
    }
}
