//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APISession2Auth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jogos
    {
        public int cod_camp { get; set; }
        public int cod_time1 { get; set; }
        public int cod_time2 { get; set; }
        public int cod_estadio { get; set; }
        public System.DateTime data { get; set; }
        public Nullable<int> resultado { get; set; }
    
        public virtual campeonatos campeonatos { get; set; }
        public virtual estadios estadios { get; set; }
        public virtual times times { get; set; }
        public virtual times times1 { get; set; }
    }
}
