//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APISession2Auth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class participacoes
    {
        public int cod_camp { get; set; }
        public int cod_time { get; set; }
        public int pontos { get; set; }
        public int classif { get; set; }
    
        public virtual campeonatos campeonatos { get; set; }
        public virtual times times { get; set; }
    }
}
