//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APISession2Auth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class patrocinios
    {
        public int ano { get; set; }
        public int cod_time { get; set; }
        public int cod_pat { get; set; }
        public decimal valor { get; set; }
    
        public virtual patrocinadores patrocinadores { get; set; }
        public virtual times times { get; set; }
    }
}
